# Generated by Django 4.2.2 on 2023-06-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='received_applications',
            field=models.IntegerField(blank=True, default=3),
            preserve_default=False,
        ),
    ]
