# Generated by Django 4.2.2 on 2023-06-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='received_applications',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
